In [19]:
import os
import pandas as pd
import pycaret.regression as reg

import utils as my

## Monitoring & Check `history.csv`

### Training results

In [24]:
df_history = pd.read_csv("./models/history.csv")
# df_history = df_history.loc[(df_history["R2"] > 0.8) & (df_history["RMSE"] < 4), :]
my.show_history(df_history, mode="Train", sort_by=['R2', 'RMSE'])

### Test restuls

In [23]:
df_history = pd.read_csv("./models/history.csv")
# df_history = df_history.loc[(df_history["R2"] > 0.8) & (df_history["RMSE"] < 4), :]
my.show_history(df_history, mode="Test", sort_by=['R2', 'RMSE'])

## Metrics

In [4]:
dataset = pd.read_csv("./boston-housing.csv",
                      header=None, delimiter=r"\s+",
                      names=['CRIM', 'ZN', 'INDUS', 'CHAS', 'NOX', 'RM', 'AGE',
                             'DIS', 'RAD', 'TAX', 'PTRATIO', 'B', 'LSTAT', 'MEDV'])
target_name = "MEDV"
train_size = 0.75
seed = 111

train, test = my.get_data(dataset, train_size, seed)

Train Data: (380, 14)
Test  Data: (126, 14)

### Default model (all default parameters)

In [5]:
## Default model
model_name = "base__train__R2-0.9810_RMSE-1.2797__test__R2-0.8130_RMSE-3.8541__seed-111"
model = reg.load_model(os.path.join("./models", model_name))
train_scores = my.get_scores(model, train, train[target_name])
test_scores = my.get_scores(model, test, test[target_name])

print(">>", type(model.steps[-1][-1]))
# print(">>", [x[0] for x in model.steps[-1][-1].estimators])
# print(">>", model.steps[-1][-1])
print(">> Train scores:\n", train_scores)
print(">> Test scores:\n", test_scores)

Transformation Pipeline and Model Successfully Loaded
>> <class 'sklearn.ensemble._stacking.StackingRegressor'>
>> Train scores:
   Model     MAE     MSE    RMSE     R2   RMSLE    MAPE Tact
0        0.9966  1.6376  1.2797  0.981  0.1213  0.0554
>> Test scores:
   Model     MAE     MSE    RMSE     R2   RMSLE    MAPE Tact
0        2.4296  14.854  3.8541  0.813  0.2519  0.1234

### Baseline model

In [7]:
model_name = "base__train__R2-0.9822_RMSE-1.2389__test__R2-0.8332_RMSE-3.6392__seed-111"
model = reg.load_model(os.path.join("./models", model_name))
train_scores = my.get_scores(model, train, train[target_name])
test_scores = my.get_scores(model, test, test[target_name])

print(">>", type(model.steps[-1][-1]))
# print(">>", [x[0] for x in model.steps[-1][-1].estimators])
# print(">>", model.steps[-1][-1])
print(">> Train scores:\n", train_scores)
print(">> Test scores:\n", test_scores)

Transformation Pipeline and Model Successfully Loaded
>> <class 'sklearn.ensemble._stacking.StackingRegressor'>
>> Train scores:
   Model     MAE     MSE    RMSE      R2   RMSLE   MAPE Tact
0        0.9566  1.5349  1.2389  0.9822  0.1155  0.052
>> Test scores:
   Model    MAE      MSE    RMSE      R2   RMSLE    MAPE Tact
0        2.294  13.2439  3.6392  0.8332  0.2385  0.1163

### Tuned models

In [8]:
model_name = "base__train__R2-0.9964_RMSE-0.5582__test__R2-0.8626_RMSE-3.3031__seed-111"
model = reg.load_model(os.path.join("./models", model_name))
train_scores = my.get_scores(model, train, train[target_name])
test_scores = my.get_scores(model, test, test[target_name])

print(">>", type(model.steps[-1][-1]))
# print(">>", [x[0] for x in model.steps[-1][-1].estimators])
# print(">>", model.steps[-1][-1])
print(">> Train scores:\n", train_scores)
print(">> Test scores:\n", test_scores)

Transformation Pipeline and Model Successfully Loaded
>> <class 'sklearn.ensemble._voting.VotingRegressor'>
>> Train scores:
   Model     MAE     MSE    RMSE      R2   RMSLE    MAPE Tact
0        0.3955  0.3116  0.5582  0.9964  0.0298  0.0212
>> Test scores:
   Model     MAE      MSE    RMSE      R2   RMSLE    MAPE Tact
0        2.1342  10.9106  3.3031  0.8626  0.1347  0.1039